on:
  pull_request:
    branches: master
    
jobs:
  build:
    runs-on: ubuntu-20.04
    container : embeddedsandbox/aarch64-none-elf-10.2-2020.11:latest
    defaults:
      run:
        shell: bash
#        working-directory: $GITHUB_WORKSPACE

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: bulid sources
        run: |
          make
    
